window.NURSERIES = [
  {
    "priority": "S",
    "category": "本命",
    "name": "このえ清新町保育園",
    "type": "認可・私立",
    "address": "東京都江戸川区清新町2-7-8",
    "phone": "03-5878-1670",
    "lat": 35.656237,
    "lng": 139.85637,
    "web": "https://kodomo.solasto-hoiku.com/nursery/konoe-seishincho/",
    "note": "0歳受入あり。清新町2丁目で送迎負荷が低い本命候補。"
  },
  {
    "priority": "S",
    "category": "本命",
    "name": "清新おひさま保育園",
    "type": "認可・私立",
    "address": "東京都江戸川区清新町1-1-37",
    "phone": "03-5878-0167",
    "lat": 35.659177,
    "lng": 139.855301,
    "web": "https://edogawa-ohisama.or.jp/seishin-ohisama/",
    "note": "清新町エリア。1歳〜の可能性があるため0歳4月対象は要確認。"
  },
  {
    "priority": "S",
    "category": "本命",
    "name": "清新第二おひさま保育園",
    "type": "認可・私立",
    "address": "東京都江戸川区清新町1-2-1 101",
    "phone": "03-3878-1922",
    "lat": 35.65976,
    "lng": 139.85595,
    "web": "https://edogawa-ohisama.or.jp/seishindaini-ohisama/",
    "note": "清新町エリア。1歳〜の可能性があるため0歳4月対象は要確認。"
  },
  {
    "priority": "S",
    "category": "本命",
    "name": "西葛西ちとせ保育園",
    "type": "認可・私立",
    "address": "東京都江戸川区西葛西2-17-15",
    "phone": "03-5679-7200",
    "lat": 35.66625,
    "lng": 139.85445,
    "web": "https://www.chitosek.or.jp/preschools/nishikasai",
    "note": "0歳受入あり。車送迎不可、徒歩・自転車前提。"
  },
  {
    "priority": "S",
    "category": "本命",
    "name": "さくらさくみらい 西葛西",
    "type": "認可・私立",
    "address": "東京都江戸川区西葛西6-4-2",
    "phone": "03-5878-1439",
    "lat": 35.66262,
    "lng": 139.86015,
    "web": "https://www.sakura-39.jp/hoiku/nishikasai",
    "note": "駅近。1歳〜の可能性があるため0歳4月対象は要確認。"
  },
  {
    "priority": "A",
    "category": "第二候補",
    "name": "キッズラボ西葛西園",
    "type": "認可・私立",
    "address": "東京都江戸川区西葛西8-4-13 リビオシティ西葛西親水公園1階",
    "phone": "03-6808-6700",
    "lat": 35.6536,
    "lng": 139.86005,
    "web": "https://kids-lab.co.jp/nishikasaien/",
    "note": "0歳受入あり。小規模寄りの認可園。"
  },
  {
    "priority": "A",
    "category": "第二候補",
    "name": "ほっぺるランド西葛西",
    "type": "認可・私立・小規模",
    "address": "東京都江戸川区西葛西2-22-45 レジデントプレイス西葛西1階",
    "phone": "03-6808-0518",
    "lat": 35.66665,
    "lng": 139.85525,
    "web": "https://hoppel-land.com/introduces/177-2/",
    "note": "0〜2歳。3歳以降の転園導線を確認。"
  },
  {
    "priority": "A",
    "category": "第二候補",
    "name": "ちゃいれっく西葛西駅ビル保育園",
    "type": "認可・私立",
    "address": "東京都江戸川区西葛西6-7-1 西葛西メトロセンターA棟2-4号",
    "phone": "03-5667-9680",
    "lat": 35.664,
    "lng": 139.85995,
    "web": "https://chilec.procare.co.jp/nishikasaieki/",
    "note": "駅直結級。1歳〜の可能性があるため0歳4月対象は要確認。"
  },
  {
    "priority": "A",
    "category": "第二候補",
    "name": "西葛西おひさま保育園",
    "type": "認可・私立",
    "address": "東京都江戸川区西葛西5-10-12",
    "phone": "03-3688-9892",
    "lat": 35.6662,
    "lng": 139.86225,
    "web": "https://edogawa-ohisama.or.jp/nishikasai-ohisama/",
    "note": "駅北側。1歳〜の可能性があるため0歳4月対象は要確認。"
  },
  {
    "priority": "A",
    "category": "第二候補",
    "name": "新田第二保育園",
    "type": "認可・区立",
    "address": "東京都江戸川区西葛西8-15-6",
    "phone": "03-3675-1588",
    "lat": 35.654703,
    "lng": 139.861459,
    "web": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "note": "区立。0歳枠の有無は要確認。"
  },
  {
    "priority": "B",
    "category": "保険",
    "name": "新田保育園",
    "type": "認可・区立",
    "address": "東京都江戸川区西葛西8-2-1",
    "phone": "03-3688-4908",
    "lat": 35.6535,
    "lng": 139.8589,
    "web": "https://www.city.edogawa.tokyo.jp/e048/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/shinden/index.html",
    "note": "区立。0歳枠の有無は要確認。"
  },
  {
    "priority": "B",
    "category": "保険",
    "name": "葛西大きなおうち保育園",
    "type": "認可・私立",
    "address": "東京都江戸川区中葛西2-26-6",
    "phone": "03-5878-0888",
    "lat": 35.665,
    "lng": 139.8723,
    "web": "https://tokyojidokyokai.com/facility/kasai",
    "note": "葛西寄り。距離は出るが広めに書く場合の保険。"
  },
  {
    "priority": "BCP",
    "category": "認可外",
    "name": "ハイブリッドマム清新町",
    "type": "企業主導型",
    "address": "東京都江戸川区清新町2-2-20 バウス西葛西清新町112号",
    "phone": "03-5659-4257",
    "lat": 35.6559,
    "lng": 139.8542,
    "web": "https://www.hybridmom.co.jp/hybridmom/HybridMom_Seishincho/",
    "note": "認可落選時のBCP。0〜2歳、空き・料金・地域枠確認。"
  },
  {
    "priority": "BCP",
    "category": "認可外",
    "name": "カメリアキッズ西葛西園",
    "type": "企業主導型・認可外",
    "address": "東京都江戸川区西葛西6-8-4 ニュースカイビル1F",
    "phone": "03-5878-1877",
    "lat": 35.66365,
    "lng": 139.86035,
    "web": "https://camellia-kids.jp/facility/249/",
    "note": "駅近の認可外BCP。空き・料金確認。"
  },
  {
    "priority": "BCP",
    "category": "認可外",
    "name": "西葛西きらきら保育園",
    "type": "企業主導型",
    "address": "東京都江戸川区西葛西6-17-1 フジマンション第二206",
    "phone": "03-5659-0810",
    "lat": 35.66325,
    "lng": 139.86145,
    "web": "https://www.starts-care.jp/service/childcare/kirakira_nishikasai/",
    "note": "0〜2歳の企業主導型。認可落選時の保険。"
  },
  {
    "priority": "BCP",
    "category": "認可外",
    "name": "西葛西きらきら保育園ANNEX",
    "type": "企業主導型",
    "address": "東京都江戸川区中葛西5-1-6",
    "phone": "03-5675-5272",
    "lat": 35.6656,
    "lng": 139.86535,
    "web": "https://www.starts-care.jp/service/childcare/kirakira_nishikasai_annex/",
    "note": "0〜2歳の企業主導型。認可落選時の保険。"
  },
  {
    "priority": "BCP",
    "category": "認可外",
    "name": "おれんじハウス中葛西保育園",
    "type": "企業主導型・認可外",
    "address": "東京都江戸川区中葛西6-17-9 クローバーメディカルビル1階",
    "phone": "03-5878-0501",
    "lat": 35.6606,
    "lng": 139.8679,
    "web": "https://orangebaby.org/what-we-can-do/feature/nakakasai/",
    "note": "0〜2歳。葛西寄りのBCP候補。"
  }
];
