window.NURSERIES = [
  {
    "name": "このえ清新町保育園",
    "kind": "認可",
    "operator": "私立",
    "area": "清新町",
    "address": "東京都江戸川区清新町2丁目7番8号",
    "phone": "03-5878-1670",
    "zero": "可",
    "zeroCapacity": 9,
    "startAge": "57日目",
    "ext": "20",
    "priority": "S",
    "route": "徒歩/自転車圏",
    "walk": 9,
    "bike": 3,
    "status": "未調査",
    "web": "https://kodomo.solasto-hoiku.com/nursery/konoe-seishincho/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区清新町2丁目7番8号",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6551,
    "lng": 139.8528,
    "note": "清新町内。0歳定員9。最優先見学。"
  },
  {
    "name": "西葛西ちとせ保育園",
    "kind": "認可",
    "operator": "私立",
    "area": "西葛西",
    "address": "東京都江戸川区西葛西2丁目17番15号",
    "phone": "03-5679-7200",
    "zero": "可",
    "zeroCapacity": 6,
    "startAge": "57日目",
    "ext": "20",
    "priority": "S",
    "route": "自転車圏",
    "walk": 18,
    "bike": 6,
    "status": "未調査",
    "web": "https://www.chitosek.or.jp/preschools/nishikasai",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区西葛西2丁目17番15号",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6681,
    "lng": 139.8566,
    "note": "西葛西北側。0歳定員6。"
  },
  {
    "name": "キッズラボ西葛西園",
    "kind": "認可",
    "operator": "私立",
    "area": "西葛西",
    "address": "東京都江戸川区西葛西8丁目4番13号",
    "phone": "03-6808-6700",
    "zero": "可",
    "zeroCapacity": 6,
    "startAge": "57日目",
    "ext": "10",
    "priority": "S",
    "route": "徒歩/自転車圏",
    "walk": 12,
    "bike": 4,
    "status": "未調査",
    "web": "https://kids-lab.co.jp/nishikasaien/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区西葛西8丁目4番13号",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.658,
    "lng": 139.8588,
    "note": "清新町から現実導線。0歳定員6。"
  },
  {
    "name": "白百合保育園",
    "kind": "認可",
    "operator": "私立",
    "area": "北葛西",
    "address": "東京都江戸川区北葛西4丁目3番9号",
    "phone": "03-3877-8344",
    "zero": "可",
    "zeroCapacity": 6,
    "startAge": "6か月目",
    "ext": "-",
    "priority": "A",
    "route": "自転車圏",
    "walk": 25,
    "bike": 8,
    "status": "未調査",
    "web": "https://www.shirayuri-creche.ed.jp/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区北葛西4丁目3番9号",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6744,
    "lng": 139.8552,
    "note": "開始月齢6か月目。延長保育なし表記に注意。"
  },
  {
    "name": "ふきのとう保育園",
    "kind": "認可",
    "operator": "私立",
    "area": "中葛西",
    "address": "東京都江戸川区中葛西6丁目4番7号",
    "phone": "03-3675-1876",
    "zero": "可",
    "zeroCapacity": 9,
    "startAge": "57日目",
    "ext": "25",
    "priority": "A",
    "route": "自転車圏",
    "walk": 24,
    "bike": 8,
    "status": "未調査",
    "web": "https://www.fukinoto.ed.jp/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区中葛西6丁目4番7号",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6607,
    "lng": 139.8685,
    "note": "0歳定員9。導線許容なら有力。"
  },
  {
    "name": "グローバルキッズ宇喜田町園",
    "kind": "認可",
    "operator": "私立",
    "area": "宇喜田町",
    "address": "東京都江戸川区宇喜田町1279",
    "phone": "03-6808-7117",
    "zero": "可",
    "zeroCapacity": 6,
    "startAge": "57日目",
    "ext": "20",
    "priority": "A",
    "route": "自転車圏",
    "walk": 24,
    "bike": 8,
    "status": "未調査",
    "web": "https://www.gkids.co.jp/facilities/nursery_166.html",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区宇喜田町1279",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.676,
    "lng": 139.8615,
    "note": "北側導線。清新町からは自転車前提。"
  },
  {
    "name": "葛西大きなおうち保育園",
    "kind": "認可",
    "operator": "私立",
    "area": "中葛西",
    "address": "東京都江戸川区中葛西2丁目26番6号",
    "phone": "03-5878-0888",
    "zero": "可",
    "zeroCapacity": 6,
    "startAge": "57日目",
    "ext": "20",
    "priority": "A",
    "route": "自転車圏",
    "walk": 28,
    "bike": 10,
    "status": "未調査",
    "web": "https://tokyojidokyokai.com/facilities/kasai/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区中葛西2丁目26番6号",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6666,
    "lng": 139.8761,
    "note": "候補には残すが距離は要確認。"
  },
  {
    "name": "ほっぺるランド中葛西",
    "kind": "認可",
    "operator": "私立",
    "area": "中葛西",
    "address": "東京都江戸川区中葛西1丁目1番15号",
    "phone": "03-6456-0590",
    "zero": "可",
    "zeroCapacity": 9,
    "startAge": "57日目",
    "ext": "20",
    "priority": "A",
    "route": "自転車圏",
    "walk": 30,
    "bike": 10,
    "status": "未調査",
    "web": "https://hoppel-land.com/introduces/177-2/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区中葛西1丁目1番15号",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6738,
    "lng": 139.8723,
    "note": "旧候補の『ほっぺるランド西葛西』は公式一覧では中葛西。"
  },
  {
    "name": "さくらさくみらい中葛西",
    "kind": "認可",
    "operator": "私立",
    "area": "中葛西",
    "address": "東京都江戸川区中葛西7丁目27番10号",
    "phone": "03-6808-2339",
    "zero": "可",
    "zeroCapacity": 6,
    "startAge": "57日目",
    "ext": "10",
    "priority": "B",
    "route": "自転車圏",
    "walk": 25,
    "bike": 9,
    "status": "未調査",
    "web": "https://www.sakura-39.jp/hoiku/nakakasai/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区中葛西7丁目27番10号",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6581,
    "lng": 139.872,
    "note": "距離・導線次第。"
  },
  {
    "name": "クオリスキッズ葛西保育園",
    "kind": "認可",
    "operator": "私立",
    "area": "中葛西",
    "address": "東京都江戸川区中葛西6丁目1番18号",
    "phone": "03-6661-3245",
    "zero": "可",
    "zeroCapacity": 6,
    "startAge": "57日目",
    "ext": "無",
    "priority": "B",
    "route": "自転車圏",
    "walk": 24,
    "bike": 8,
    "status": "未調査",
    "web": "https://quolis-kids.com/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区中葛西6丁目1番18号",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6618,
    "lng": 139.867,
    "note": "延長保育定員無。導線確認。"
  },
  {
    "name": "サクラナーサリー",
    "kind": "認可",
    "operator": "私立",
    "area": "中葛西",
    "address": "東京都江戸川区中葛西3丁目15番6号",
    "phone": "03-3686-0067",
    "zero": "可",
    "zeroCapacity": 6,
    "startAge": "57日目",
    "ext": "10",
    "priority": "B",
    "route": "自転車圏",
    "walk": 27,
    "bike": 10,
    "status": "未調査",
    "web": "https://sakura-nursery.kids.coocan.jp/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区中葛西3丁目15番6号",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6639,
    "lng": 139.8733,
    "note": "葛西駅寄り。優先度低めだが候補維持。"
  },
  {
    "name": "葛西駅前さくら保育園",
    "kind": "認可",
    "operator": "私立",
    "area": "東葛西",
    "address": "東京都江戸川区東葛西5丁目1番3号 ボアビル2階",
    "phone": "03-3878-0026",
    "zero": "可",
    "zeroCapacity": 20,
    "startAge": "57日目",
    "ext": "30",
    "priority": "C",
    "route": "遠方保険",
    "walk": 38,
    "bike": 14,
    "status": "未調査",
    "web": "https://sakura-kasai.com/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区東葛西5丁目1番3号+ボアビル2階",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6639,
    "lng": 139.8739,
    "note": "東葛西。削除せず遠方保険。0歳定員は大きい。"
  },
  {
    "name": "たんぽぽ保育園",
    "kind": "認可",
    "operator": "私立",
    "area": "東葛西",
    "address": "東京都江戸川区東葛西8丁目19番2号",
    "phone": "03-5878-0290",
    "zero": "可",
    "zeroCapacity": 12,
    "startAge": "57日目",
    "ext": "25",
    "priority": "C",
    "route": "遠方保険",
    "walk": 50,
    "bike": 18,
    "status": "未調査",
    "web": "https://www.nanohana-kai.or.jp/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区東葛西8丁目19番2号",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6512,
    "lng": 139.8839,
    "note": "東葛西。現視野では取りにくいが保険として保持。"
  },
  {
    "name": "グローバルキッズ南葛西園",
    "kind": "認可",
    "operator": "私立",
    "area": "南葛西",
    "address": "東京都江戸川区南葛西6丁目19番13号1階",
    "phone": "03-3877-4581",
    "zero": "可",
    "zeroCapacity": 6,
    "startAge": "57日目",
    "ext": "20",
    "priority": "C",
    "route": "遠方保険",
    "walk": 42,
    "bike": 15,
    "status": "未調査",
    "web": "https://www.gkids.co.jp/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区南葛西6丁目19番13号1階",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6422,
    "lng": 139.8755,
    "note": "南葛西。優先度を下げて保持。"
  },
  {
    "name": "にじのいるか保育園南葛西",
    "kind": "認可",
    "operator": "私立",
    "area": "南葛西",
    "address": "東京都江戸川区南葛西5丁目7番2号1階",
    "phone": "03-6240-5010",
    "zero": "可",
    "zeroCapacity": 6,
    "startAge": "57日目",
    "ext": "無",
    "priority": "C",
    "route": "遠方保険",
    "walk": 45,
    "bike": 16,
    "status": "未調査",
    "web": "https://www.nijinoiruka.ed.jp/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区南葛西5丁目7番2号1階",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.641,
    "lng": 139.8725,
    "note": "南葛西。遠方保険。"
  },
  {
    "name": "太陽の子東葛西保育園",
    "kind": "認可",
    "operator": "私立",
    "area": "東葛西",
    "address": "東京都江戸川区東葛西7丁目28番15号オンダビル1F",
    "phone": "03-6663-8235",
    "zero": "可",
    "zeroCapacity": 6,
    "startAge": "57日目",
    "ext": "15",
    "priority": "C",
    "route": "遠方保険",
    "walk": 45,
    "bike": 16,
    "status": "未調査",
    "web": "https://www.kidslife-nursery.com/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区東葛西7丁目28番15号オンダビル1F",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6567,
    "lng": 139.8849,
    "note": "東葛西。遠方保険。"
  },
  {
    "name": "アスク東葛西保育園",
    "kind": "認可",
    "operator": "私立",
    "area": "東葛西",
    "address": "東京都江戸川区東葛西6丁目28番6号",
    "phone": "03-5659-0601",
    "zero": "可",
    "zeroCapacity": 6,
    "startAge": "57日目",
    "ext": "20",
    "priority": "C",
    "route": "遠方保険",
    "walk": 44,
    "bike": 16,
    "status": "未調査",
    "web": "https://www.nihonhoiku.co.jp/blog/higashikasai/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区東葛西6丁目28番6号",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6589,
    "lng": 139.8819,
    "note": "東葛西。遠方保険。"
  },
  {
    "name": "キッズラボ東葛西園",
    "kind": "認可",
    "operator": "私立",
    "area": "東葛西",
    "address": "東京都江戸川区東葛西9丁目3番14号",
    "phone": "03-6808-6570",
    "zero": "可",
    "zeroCapacity": 6,
    "startAge": "57日目",
    "ext": "10",
    "priority": "C",
    "route": "遠方保険",
    "walk": 55,
    "bike": 20,
    "status": "未調査",
    "web": "https://kids-lab.co.jp/higashikasaien/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区東葛西9丁目3番14号",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kuseijoho/gaiyo/shisetsuguide/bunya/kosodate/hoikuen/index.html",
    "lat": 35.6495,
    "lng": 139.8884,
    "note": "東葛西。遠方保険。"
  },
  {
    "name": "HybridMom Nursery Preschool Seishincho",
    "kind": "認可外/企業主導型",
    "operator": "企業主導型",
    "area": "清新町",
    "address": "東京都江戸川区清新町2丁目2番20号 バウス西葛西清新町内",
    "phone": "03-5659-4257",
    "zero": "可",
    "zeroCapacity": 21,
    "startAge": "0歳",
    "ext": "20:30まで",
    "priority": "BCP-S",
    "route": "徒歩/自転車圏",
    "walk": 6,
    "bike": 2,
    "status": "空き要確認",
    "web": "https://www.hybridmom.co.jp/hybridmom/HybridMom_Seishincho/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区清新町2丁目2番20号+バウス西葛西清新町内",
    "source": "https://www.hybridmom.co.jp/hybridmom/HybridMom_Seishincho/",
    "lat": 35.6568,
    "lng": 139.8507,
    "note": "清新町内。認可外BCP最重要。月額等は要確認。"
  },
  {
    "name": "カメリアキッズ西葛西園",
    "kind": "認可外/企業主導型",
    "operator": "企業主導型",
    "area": "西葛西",
    "address": "東京都江戸川区西葛西6丁目8番4号 ニュースカイビル1F",
    "phone": "",
    "zero": "可",
    "zeroCapacity": null,
    "startAge": "0～2歳",
    "ext": "要確認",
    "priority": "BCP-S",
    "route": "駅前",
    "walk": 17,
    "bike": 6,
    "status": "募集中情報あり/要確認",
    "web": "https://camellia-kids.jp/facility/249/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区西葛西6丁目8番4号+ニュースカイビル1F",
    "source": "https://camellia-kids.jp/facility/249/",
    "lat": 35.663,
    "lng": 139.8597,
    "note": "西葛西駅近。2027年度4月入園募集記載あり。"
  },
  {
    "name": "おれんじオハナ西葛西保育園",
    "kind": "認可外/企業主導型",
    "operator": "企業主導型",
    "area": "西葛西",
    "address": "東京都江戸川区西葛西5丁目8番3号 小島町二丁目団地3号棟1階",
    "phone": "03-6661-3519",
    "zero": "可",
    "zeroCapacity": 12,
    "startAge": "生後57日から",
    "ext": "18:30まで",
    "priority": "BCP-A",
    "route": "駅近",
    "walk": 18,
    "bike": 6,
    "status": "空きなし記載/要再確認",
    "web": "https://orangebaby.org/what-we-can-do/feature/o-nishikasai/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区西葛西5丁目8番3号+小島町二丁目団地3号棟1階",
    "source": "https://orangebaby.org/what-we-can-do/feature/o-nishikasai/",
    "lat": 35.6663,
    "lng": 139.8621,
    "note": "空き状況は変動。BCPとして電話確認。"
  },
  {
    "name": "おれんじハウス西葛西保育園",
    "kind": "地域型/小規模（要確認）",
    "operator": "小規模/企業主導型確認",
    "area": "西葛西",
    "address": "東京都江戸川区西葛西5丁目8番3号 小島町二丁目団地3号棟1階",
    "phone": "03-6456-0412",
    "zero": "可",
    "zeroCapacity": 19,
    "startAge": "生後57日から",
    "ext": "19:30まで",
    "priority": "BCP-A",
    "route": "駅近",
    "walk": 18,
    "bike": 6,
    "status": "空きなし記載/要再確認",
    "web": "https://orangebaby.org/what-we-can-do/feature/h-nishikasai/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区西葛西5丁目8番3号+小島町二丁目団地3号棟1階",
    "source": "https://orangebaby.org/what-we-can-do/feature/h-nishikasai/",
    "lat": 35.6664,
    "lng": 139.8621,
    "note": "制度区分は要確認。BCPとして管理。"
  },
  {
    "name": "stellar education garden 西葛西保育園",
    "kind": "認可外/企業主導型",
    "operator": "企業主導型",
    "area": "西葛西",
    "address": "東京都江戸川区西葛西7丁目9番13号 保戸田マンション1階",
    "phone": "03-6663-8624",
    "zero": "要確認",
    "zeroCapacity": 4,
    "startAge": "要確認",
    "ext": "18:30まで",
    "priority": "BCP-B",
    "route": "西葛西駅南",
    "walk": 19,
    "bike": 7,
    "status": "受入状況不可記載/要確認",
    "web": "https://stellar-ed.com/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区西葛西7丁目9番13号+保戸田マンション1階",
    "source": "https://www.city.edogawa.tokyo.jp/e047/kosodate/kosodate/keikaku/hoikujigyo.html",
    "lat": 35.66,
    "lng": 139.8606,
    "note": "江戸川区企業主導型一覧では地域枠あり。ただし受入状況は要確認。"
  },
  {
    "name": "モリモリキッズ",
    "kind": "認可外/企業主導型",
    "operator": "企業主導型",
    "area": "北葛西",
    "address": "東京都江戸川区北葛西4丁目3番30号",
    "phone": "03-5679-7899",
    "zero": "可",
    "zeroCapacity": 10,
    "startAge": "生後57日から",
    "ext": "18:30まで",
    "priority": "BCP-B",
    "route": "北葛西",
    "walk": 26,
    "bike": 9,
    "status": "要確認",
    "web": "https://mk.moriyamaikai.or.jp/morimorikids/index.html",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区北葛西4丁目3番30号",
    "source": "https://mk.moriyamaikai.or.jp/morimorikids/index.html",
    "lat": 35.6749,
    "lng": 139.854,
    "note": "北葛西。認可外BCPとして保持。"
  },
  {
    "name": "Global Indian International School, SSD, Tokyo",
    "kind": "認可外/インター",
    "operator": "認可外",
    "area": "清新町",
    "address": "東京都江戸川区清新町2丁目10番1号",
    "phone": "03-3686-3055",
    "zero": "要確認",
    "zeroCapacity": null,
    "startAge": "要確認",
    "ext": "要確認",
    "priority": "BCP-C",
    "route": "清新町",
    "walk": 10,
    "bike": 3,
    "status": "要確認",
    "web": "https://tokyo.globalindianschool.org/",
    "map": "https://www.google.com/maps/search/?api=1&query=東京都江戸川区清新町2丁目10番1号",
    "source": "https://www.fukunavi.or.jp/fukunavi/controller?AREA1=&AREA2=&AREA3=&AREA4=9&AREA5=99998&AREA6=&HJN_CD=900009498&HYK_FLG=&NAME=&NAME2=%E3%83%8B%E3%83%B3%E3%82%AB%E3%82%AC%E3%82%A4%E3%83%9B%E3%82%A4%E3%82%AF%E3%82%A6%E3%83%B3%E3%82%A8%E3%82%A4%E3%82%B8%E3%82%AE%E3%83%A7%E3%82%A6%E3%82%B7%E3%83%A3&OCP_FL=&ROW=780&SCHSVCSBRCD1=&SCHSVCSBRCD2=&SCHSVCSBRCD3=&STEP_SVCSBRCD=&SVCDBRCD=&SVCSBRCDALL=&actionID=jgyhjn&beforeID=&cmd=hjnjgy&preRow=0",
    "lat": 35.6536,
    "lng": 139.8532,
    "note": "現実的な保育園代替になるかは要確認。優先度低。"
  }
];
